# Практическое задание
Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

# 1
а) оба не опеределны
б) АВ даст матрицу 2 на 5, ВА не определена
в) АВ - 8 на 8, ВА - 3 на 3
г) АВ и ВА - 4 на 4

# 2
Сумма:
$\begin{pmatrix}
5 & -3\\ 
3 & 5 
\end{pmatrix}$.


Произвдедение
$\begin{pmatrix}
1 * 4 + (-2) * 0 & 1 * (-1) + (-2) * 5\\ 
3 * 4 + 0 * 0 & 3 * (-1) + 0 * 5 
\end{pmatrix}
=
\begin{pmatrix}
4 &  -11\\ 
12 & -3 
\end{pmatrix}$.

In [1]:
import numpy as np

In [2]:
A = np.array([1,-2,3,0]).reshape(2,2)
B = np.array([4,-1,0,5]).reshape(2,2)

In [3]:
A+B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

# 3
$\begin{pmatrix}
11 & -5\\ 
9 & -12 
\end{pmatrix}$.

In [5]:
A = np.array([1,7,3,-6]).reshape(2,2)
B = np.array([0,5,2,-1]).reshape(2,2)
C = np.array([2,-4,1,1]).reshape(2,2)
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

# 4

$AA^{T} = \begin{pmatrix}
17&18&11\\
18&29&4\\
11&4&13
\end{pmatrix}$.

$A^{T}A = \begin{pmatrix}
45&0\\
0&14
\end{pmatrix}$.

In [6]:
A = np.array([4,1,5,-2,2,3]).reshape(3,2)
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

# Практическое задание 2
__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# 1

* а) sin(x) * sin(x) - (-cos(x)) * cos(x) = __1__
* б) 4 * 5 * 9 = __180__
* в) Если из второй и из третьей строки вычесть первую, то вторая и третья строки будут линенйно зависисмыми: (3,3,3) и (6,6,6) соответственно. __Тогда опеределитель равен 0__

In [8]:
A=np.array([4,2,3,0,5,1,0,0,9]).reshape(3,3)
np.linalg.det(A)

180.0

In [9]:
A=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
np.linalg.det(A)

0.0

# 2
* а) 4 * 4 = __16__
* б) __4__
* в) $2^{n} * 4$, где n - порядок матрицы

In [10]:
A=np.array([4,4,3,4]).reshape(2,2)
np.linalg.det(A)

4.0

In [11]:
np.linalg.det(A.dot(A))

16.000000000000043

In [12]:
np.linalg.det(A.T)

4.0

# 3 
Строки 1 и 2 линейнозависисмые, значит определитель матрицы равен нулю

# 4
а) строка 3 - лин.комбинация - выбросим. У всех миноров определеитель не равен 0. Ранг - 2
б) 

б) $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$
Выбросим 1 столбец - линейную комбинацию от 2-го столбца
$$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
0 & 4 & 3\\ 
3 & 5 & 6
\end{pmatrix}.$$

удвоенную первую строку вычтем из треттье строки

$$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
0 & 0 & 1\\ 
3 & 5 & 6
\end{pmatrix}.$$

итого минор
$$\begin{pmatrix}
3 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 0 & 1
\end{pmatrix}.$$

имеет определеитель, __ранг 3__

In [13]:
A=np.array([1,2,3,1,1,1,2,3,4]).reshape(3,3)
np.linalg.matrix_rank(A)

2

In [14]:
A=np.array([0,0,2,1,0,0,2,2,0,0,4,3,2,3,5,6]).reshape(4,4)
np.linalg.matrix_rank(A)

3